version: '3.4'

services:
  webapp:
    image: django
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 django/easyDMP/manage.py runserver 0.0.0.0:8080"]
    ports:
      - 8080:8080
      - 5678:5678
    volumes:
      - .:/app
    user: root:root
    
  db:
    image: postgres
    build:
      context: .
      dockerfile: ./postgres-multiple-db/Dockerfile
    environment:
      POSTGRES_MULTIPLE_DATABASES: easydmp, decos_metadata_db
      POSTGRES_USER: easydmp
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: